"""add login_date field to users table

Revision ID: 2910d452a6c9
Revises: 3b0510f26361
Create Date: 2026-01-15 13:57:46.476271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2910d452a6c9'
down_revision: Union[str, Sequence[str], None] = '3b0510f26361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('register_date', sa.BigInteger(), nullable=True))
    op.execute("UPDATE users SET register_date = CAST(EXTRACT(EPOCH FROM NOW()) * 1000 AS BIGINT) WHERE register_date IS NULL")
    op.alter_column('users', 'register_date', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'register_date')
    # ### end Alembic commands ###
